[package]
name = "generic_daw_widget"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
utils.workspace = true

iced_widget = { git = "https://github.com/edwloef/iced.git", branch = "generic-daw", features = [
	"canvas",
] }
